DROP TABLE IF EXISTS "FILM" CASCADE;
DROP TABLE IF EXISTS "GENRE" CASCADE;
DROP TABLE IF EXISTS "GENRE_BOOK" CASCADE;
DROP TABLE IF EXISTS "RATING_BOOK" CASCADE;
DROP TABLE IF EXISTS "LIKES" CASCADE;
DROP TABLE IF EXISTS "USERS" CASCADE;
DROP TABLE IF EXISTS "FRIEND" CASCADE;

CREATE TABLE "GENRE_BOOK" (
    genre_id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    name varchar(100)
);

CREATE TABLE "RATING_BOOK" (
    rating_id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    name varchar(100)
);

CREATE TABLE "FILM" (
    film_id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    name varchar(200) NOT NULL,
    description varchar(200),
    release_date date,
    rating_id int,
    duration int,
    foreign key (rating_id) references RATING_BOOK(rating_id)
);

CREATE TABLE "GENRE" (
    film_id int,
    genre_id int,
    foreign key (film_id) references FILM(film_id),
    foreign key (genre_id) references GENRE_BOOK(genre_id),
    CONSTRAINT GENRE_PK PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE "USERS" (
    user_id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    email varchar(100),
    login varchar(100),
    name varchar(100),
    birthday date
);

CREATE TABLE "LIKES" (
    film_id int,
    user_id int,
    foreign key (film_id) references FILM(film_id),
    foreign key (user_id) references USERS(user_id) ON DELETE CASCADE,
    CONSTRAINT LIKES_PK PRIMARY KEY (film_id, user_id)
);

CREATE TABLE "FRIEND" (
    user_id_1 int,
    user_id_2 int,
    foreign key (user_id_1) references USERS(user_id) ON DELETE CASCADE,
    foreign key (user_id_2) references USERS(user_id) ON DELETE CASCADE,
    CONSTRAINT FRIEND_PK PRIMARY KEY (user_id_1, user_id_2)
);