DROP TABLE IF EXISTS "FILM" CASCADE;
DROP TABLE IF EXISTS "GENRE" CASCADE;
DROP TABLE IF EXISTS "GENRE_BOOK" CASCADE;
DROP TABLE IF EXISTS "RATING_BOOK" CASCADE;
DROP TABLE IF EXISTS "LIKES" CASCADE;
DROP TABLE IF EXISTS "USERS" CASCADE;
DROP TABLE IF EXISTS "FRIEND" CASCADE;
DROP TABLE IF EXISTS "USER_FILM_REVIEW" CASCADE;
DROP TABLE IF EXISTS "REVIEW_ESTIMATION" CASCADE;
DROP TABLE IF EXISTS "REVIEW_BOOK" CASCADE;
DROP TABLE IF EXISTS "DIRECTOR" CASCADE;
DROP TABLE IF EXISTS "DIRECTOR_BOOK" CASCADE;


CREATE TABLE "GENRE_BOOK" (
    genre_id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    name varchar(100)
);

CREATE TABLE "RATING_BOOK" (
    rating_id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    name varchar(100)
);

CREATE TABLE "DIRECTOR_BOOK" (
    dir_id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    name varchar(200)
);

CREATE TABLE "FILM" (
    film_id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    name varchar(200) NOT NULL,
    description varchar(200),
    release_date date,
    rating_id int,
    duration int,
    foreign key (rating_id) references RATING_BOOK(rating_id)
);

CREATE TABLE "GENRE" (
    film_id int,
    genre_id int,
    foreign key (film_id) references FILM(film_id),
    foreign key (genre_id) references GENRE_BOOK(genre_id),
    CONSTRAINT GENRE_PK PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE "DIRECTOR" (
    film_id int,
    dir_id int,
    foreign key (film_id) references FILM(film_id),
    foreign key (dir_id) references DIRECTOR_BOOK(dir_id),
    CONSTRAINT DIRECTOR_PK PRIMARY KEY (film_id, dir_id)
);


CREATE TABLE "USERS" (
    user_id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    email varchar(100),
    login varchar(100),
    name varchar(100),
    birthday date
);

CREATE TABLE "LIKES" (
    film_id int,
    user_id int,
    foreign key (film_id) references FILM(film_id),
    foreign key (user_id) references USERS(user_id),
    CONSTRAINT LIKES_PK PRIMARY KEY (film_id, user_id)
);

CREATE TABLE "FRIEND" (
    user_id_1 int,
    user_id_2 int,
    foreign key (user_id_1) references USERS(user_id),
    foreign key (user_id_2) references USERS(user_id),
    CONSTRAINT FRIEND_PK PRIMARY KEY (user_id_1, user_id_2)
);

CREATE TABLE "REVIEW_BOOK" (
    review_id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    content varchar(200),
    is_positive bool not null
);

CREATE TABLE "USER_FILM_REVIEW" (
    film_id int not null references FILM(film_id),
    user_id int not null references USERS(user_id),
    review_id int not null references REVIEW_BOOK(review_id)
);

CREATE TABLE "REVIEW_ESTIMATION" (
    user_id int not null references USERS(user_id),
    review_id int not null references REVIEW_BOOK(review_id),
    is_positive bool not null
);
